version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/src/api/requirements"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
  - package-ecosystem: "pip"
    directory: "/src/worker/requirements"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/src/api"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/src/worker"
    schedule:
      interval: "daily"
