version: "3.8"
services:
  api:
    restart: unless-stopped
    init: true
    entrypoint: [ "gunicorn", "-k", "uvicorn.workers.UvicornWorker", "--chdir", "./src/api", "app:app", "--bind", "0.0.0.0:5050" ]
    depends_on:
      - redis
    build:
      context: .
    container_name: convert-to-pdf-api
    networks:
      - convert-to-pdf
    volumes:
      - data:/app/data
    ports:
      - "${SERVICE_PORT:-5060}:5050"
    env_file: .env

  worker:
    restart: unless-stopped
    init: true
    entrypoint: [ "python", "-m", "src.worker.QueueProcessor" ]
    depends_on:
      - redis
    build:
      context: .
    container_name: convert-to-pdf-worker
    networks:
      - convert-to-pdf
    volumes:
      - data:/app/data
    env_file: .env
  redis:
    image: "redis:5.0.14"
    container_name: convert-to-pdf-redis
    restart: unless-stopped
    command: redis-server
    networks:
      - convert-to-pdf
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master

networks:
  convert-to-pdf:

volumes:
  data:
