version: "3"
services:
  api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: api.Dockerfile
    networks:
      - convert-to-pdf
    volumes:
      - ./data:/app/data
    ports:
      - "${SERVICE_PORT:-5060}:5050"
    environment:
      - SENTRY_PDF_CONVERT_DSN=${SENTRY_PDF_CONVERT_DSN:-}
      - SERVICE_HOST=${SERVICE_HOST:-http://127.0.0.1}
      - SERVICE_PORT=${SERVICE_PORT:-5060}

  worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: worker.Dockerfile
      args:
        - VERSION=0.2.0
        - BUILD_DATE=2022-10-14
    networks:
      - convert-to-pdf
    volumes:
      - ./config:/config
      - ./data:/app/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - S6_KEEP_ENV=1
      - SENTRY_PDF_CONVERT_DSN=${SENTRY_PDF_CONVERT_DSN:-}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - SERVICE_HOST=${SERVICE_HOST:-http://127.0.0.1}
      - SERVICE_PORT=${SERVICE_PORT:-5060}

  redis:
    image: "redis:5.0.14"
    network_mode: host
    restart: unless-stopped
    command: redis-server
    networks:
      - convert-to-pdf
    environment:
      - REDIS_REPLICATION_MODE=master
    profiles:
      - testing

networks:
  convert-to-pdf:
