name: Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Start enviroment
        run: ./run start -d
      - name: Install venv
        run: ./run install_venv
      - name: Run tests
        run: ./run test
